// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQbY578AzY3YWq65RQfg-fneukfoZoFM',
    appId: '1:782659645882:web:168fd0cb3474bb3fb9ad83',
    messagingSenderId: '782659645882',
    projectId: 'ecommerce-waordone',
    authDomain: 'ecommerce-waordone.firebaseapp.com',
    storageBucket: 'ecommerce-waordone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2WV0yvqd8IwDCt5i_Dg9QL_3oKHHctao',
    appId: '1:782659645882:android:0b635b2cc025067bb9ad83',
    messagingSenderId: '782659645882',
    projectId: 'ecommerce-waordone',
    storageBucket: 'ecommerce-waordone.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQbY578AzY3YWq65RQfg-fneukfoZoFM',
    appId: '1:782659645882:web:0ae0bad323cd7b8fb9ad83',
    messagingSenderId: '782659645882',
    projectId: 'ecommerce-waordone',
    authDomain: 'ecommerce-waordone.firebaseapp.com',
    storageBucket: 'ecommerce-waordone.firebasestorage.app',
  );
}
